
---
- hosts: ubuntu
  become: true
  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest

    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present
      notify:
         - restart apache2
    - name: upload index file
      copy:
        src: index.html
        dest: /var/www/html/index.html
        mode: 0755
      notify: restart apache2

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted

