
--- ## Copy index file in document root of webserver

- hosts: ubuntu
  become: yes
  tasks:
   # - name: create target directory
   #   file: path=/var/www/html state=directory mode=0755

    - name: deploy index.html
      copy:
       src: /home/ansible/index.html
       dest: /var/www/html/index.html

...
