---
  - hosts: nodes
    remote_user: ansible
    become: yes
    tasks:
      - name: Install the package at runtime
        package:
          name: '{{ pkg }}'
          state: present

## ansible-playbook vars.yaml --extra-vars "pkg=tree"
